### ISSUE TITLE
Foreign key error?

### ISSUE THREAD

**Issue by lmaurits** [lexibank/kitchensemitic#3]
According to this dataset's `metadata.json` file (if I'm understanding it correctly), the `Parameter_ID` column in `forms.csv` is supposed to contain pointers to the `ID` column in `parameters.csv` (as you'd expect, and as all the other LexiBank datasets I've looked at so far seem to do).  However, the actual values in the `Parameter_ID` column aren't numeric IDs at all, and seem instead to be a slightly normalised (lower case, no punctuation) version of values from the `Name` column in `parameters.csv`, making it very hard to actually tie the two tables together.  Is this expected?

**Comment by xrotwang** [comment]
No, that's a bug. The CLDF also doesn't validate without `WARNING`:
```
$ cldf validate cldf/cldf-metadata.json
...
WARNING cldf/forms.csv:2281 Key ye not found in table parameters.csv
WARNING cldf/forms.csv:2282 Key ye not found in table parameters.csv
WARNING cldf/forms.csv:2283 Key ye not found in table parameters.csv
WARNING cldf/forms.csv:2284 Key ye not found in table parameters.csv
WARNING cldf/forms.csv:2285 Key ye not found in table parameters.csv
WARNING cldf/forms.csv:2286 Key ye not found in table parameters.csv
WARNING cldf/forms.csv:2287 Key ye not found in table parameters.csv
WARNING cldf/forms.csv:2288 Key ye not found in table parameters.csv
WARNING cldf/forms.csv:2289 Key ye not found in table parameters.csv
```

Since the dataset has no released version yet, I'd say it is not ready for use yet :)

**Comment by xrotwang** [comment]
@lmaurits do you need this data for anything urgent? If so, I could try to get it in shape for at least a `v0.1` release.

**Comment by lmaurits** [comment]
No, nothing urgent at all.  I just wrote a CLDF front-end yesterday for some code a colleague wrote to calculate various interesting statistics on cognate datasets, and I was running it on random LexiBank datasets to make sure it ran without errors and produced sane-looking results.  This was one of the very few it choked on, but if it's a buggy dataset then that's unsurprising and unimportant.  Thanks, anyway!

**Comment by xrotwang** [comment]
Here's a good list of proper datasets: https://zenodo.org/oai2d?verb=ListRecords&set=user-lexibank&metadataPrefix=oai_dc

**Comment by SimonGreenhill** [comment]
@lmaurits please don't use lexibank until we release it. Discuss with @RustyGray if needed.

**Comment by xrotwang** [comment]
@SimonGreenhill using released lexibank datasets as examples of CLDF "in the wild" should be ok, though, right?

**Comment by lmaurits** [comment]
Sure thing.  We have no plans to publish anything using Lexibank at this stage (well, aside from Uralex, of course), I was just looking for well-formed CLDF cognate datasets to use as tests cases.
